name: Generate PDF from GitHub Pages

on:
  workflow_run:
    workflows: ['Deploy']
    types:
      - completed

jobs:
  generate-and-release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Puppeteer dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libx11-xcb1 libxcomposite1 libxcursor1 libxdamage1 \
            libxi6 libxtst6 libnss3 libasound2 \
            libatk-bridge2.0-0 libgtk-3-0 libxrandr2 libgbm-dev

      - name: Wait for deployment to complete
        run: sleep 20 # 必要に応じて調整

      - name: Generate PDF
        run: node generate-pdf.js

      - name: Check PDF output
        run: |
          echo "Generated files:"
          ls -lh

      - name: Upload PDF to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: PDF Release
          files: 職務経歴書.pdf
          overwrite: true
          draft: false
          prerelease: false
          token: ${{ secrets.GH_PAT }}
