name: Generate PDF and Upload to Release

on:
  workflow_run:
    workflows: ['Deploy']
    types:
      - completed

jobs:
  generate-and-release:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Puppeteer dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libx11-xcb1 libxcomposite1 libxcursor1 libxdamage1 \
            libxi6 libxtst6 libnss3 libasound2 \
            libatk-bridge2.0-0 libgtk-3-0 libxrandr2 libgbm-dev

      - name: Wait for GitHub Pages to deploy
        run: sleep 20

      - name: Generate PDF
        run: node generate-pdf.js

      - name: Confirm generated file
        run: ls -lh

      - name: Delete existing PDF asset (if exists)
        run: |
          echo "Searching for existing PDF assets..."
          gh api repos/${{ github.repository }}/releases/tags/latest \
            | jq -r '.assets[] | [.id, .name] | @tsv' \
            | grep 'resume.pdf' | while IFS=$'\t' read -r ID NAME; do
                echo "Deleting $NAME (ID: $ID)"
                gh api repos/${{ github.repository }}/releases/assets/$ID -X DELETE
              done
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}

      - name: Upload PDF to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: PDF Release
          files: resume.pdf
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
